include:
  - project: 'slicelife/data-engineering/de-databricks-cicd'
    ref: v1.30
    file: 'databricks-jar-gitlab-ci-template.yml'

###### common test step #####
.spark-salesforce-test-info:
  variables:
    PROJECT_DIRECTORY: .

spark-salesforce-test-and-package-2-11:
  variables:
    SCALA_VERSION: "2.11"
  extends:
    - .spark-salesforce-test-info
    - .test-and-package-jar
  script:
    - sbt '++ 2.11.12' test package

spark-salesforce-test-and-package-2-12:
  variables:
    SCALA_VERSION: "2.12"
  extends:
    - .spark-salesforce-test-info
    - .test-and-package-jar

publish spark salesforce:
  stage: publish
  extends:
    - .spark-salesforce-test-info
    - .test-and-package-jar
  script:
    - cat $CI_CRED_TEMPLATE | tee /root/.sbt/.credentials
    - sbt +publish
  only:
    refs:
      - master
  except:
    - schedules
  allow_failure: false

