

###### common test step #####
# Split this back out if we split into more than a single jar
.spark-salesforce-test-info:
  variables:
    PROJECT_DIRECTORY: "spark-salesforce"
    SCALA_VERSION: "2.11"

spark-salesforce-test-and-package-2-11:
  variables:
    PROJECT_DIRECTORY: "spark-salesforce"
    SCALA_VERSION: "2.11"
  extends:
    - .spark-salesforce-test-info
    - .test-and-package-jar
  script:
    - sbt '++ 2.11.12' test package
  only:
    changes:
      - spark-salesforce/**/*

spark-salesforce-test-and-package-2-12:
  variables:
    PROJECT_DIRECTORY: "spark-salesforce"
    SCALA_VERSION: "2.12"
  extends:
    - .spark-salesforce-test-info
    - .test-and-package-jar
  only:
    changes:
      - spark-salesforce/**/*

publish spark salesforce:
  stage: publish
  extends:
    - .spark-salesforce-test-info
    - .test-and-package-jar
  script:
    - cat $CI_CRED_TEMPLATE | tee /root/.sbt/.credentials
    - sbt +publish
  only:
    refs:
      - master
  except:
    - schedules
  allow_failure: false

